### ISSUE TITLE
Fixing Homepage

### ISSUE THREAD

**Issue by mrtechtroid** [Moses-main/Brain-Gain#11]
![image](https://github.com/Moses-main/Brain-Gain/assets/64828294/1e1437b1-39ab-4ae2-ae93-78c01db83b4a)
The Homepage currently has two overlapping navigation bar's. I would like to fix that, could you please assign this issue to me.

**Comment by Moses-main** [comment]
Alright go ahead and contribute to it. Also work on the mobile view if you can.

I have also added the hacktoberfest label to it

**Comment by mrtechtroid** [comment]
@Moses-main Can you please add the label hacktoberfest-accepted to the pull request #13, so that the pull request of mine, can successfully be counted towards Hacktoberfest 2023. Because to me, it is still showing NOT-PARTICIPATING in the dashboard, which may be because the pull request is having a different ID from the issue.

**Comment by Moses-main** [comment]
Ok I would do that

**Comment by mrtechtroid** [comment]
Thanks a lot.
