### ISSUE TITLE
Create Contributing.md

### ISSUE THREAD

**Issue by i-am-yuvi** [Moses-main/Brain-Gain#2]
**This is a(n):**
- [ ] Update to an existing code
- [ ] Any Error
- [x] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**
I would like to create a CONTRIBUTING.md file so that new comers can understand the basic principles to contribute to the repositories and other related information

**Comment by Moses-main** [comment]
Ok @i-am-yuvi 

The contributing.md file is important and also add steps for those Contributing to add their GitHub account and image

**Comment by Moses-main** [comment]
@i-am-yuvi Go ahead and work on the documentation you talked about. After you then have to send a pull request.

**Comment by Moses-main** [comment]
This is great. Thank you for Contributing
