### ISSUE TITLE
Fixing the practical page where calculator and navbar are a bit out of order.

### ISSUE THREAD

**Issue by RonitBaranwal** [Moses-main/Brain-Gain#8]
A very nice website about learning and exploring new domains. It is quite nice website but the I could see that there were some potential  UI changes which could be made in the website like :-

![Screenshot 2023-10-14 023446](https://github.com/Moses-main/Brain-Gain/assets/123174522/ebf0d25f-2a70-4522-979d-faf326c05789)

![Screenshot 2023-10-14 023459](https://github.com/Moses-main/Brain-Gain/assets/123174522/ed3d44d2-bac0-477f-a1f1-8fc8bbadf02d)

If Its okay for you , I can work on this issue . 
please assign it to me.

**Comment by Moses-main** [comment]
Alright I would do that immediately

**Comment by Moses-main** [comment]
@RonitBaranwal  you can go ahead and Contribute

**Comment by RonitBaranwal** [comment]
I am sorry I was busy for college recently will do it.

**Comment by Moses-main** [comment]
Ok. But I'm planning of changing most of the course there.

I think you should check the README file and equally pull the latest changes made on the platform. @RonitBaranwal
